### ISSUE TITLE
Male headers in BOM

### ISSUE THREAD

**Issue by electroniceel** [free-pdk/easy-pdk-programmer-hardware#1]
The easypdkprog_pcb12_bom.csv has the headers H1 and H2. 

The LCSC part listed is C124381. This seems to be a male header.

But all the photos of the pcb show a female header. And I'd also say it makes more sense to use a female header to plug adapters in.

A female header at LCSC would be for example C27438.

**Comment by freepdk** [comment]
You are right, they should be **FEMALE** headers.

Something I missed changing when moving to revision 1.2

**Comment by freepdk** [comment]
Fixed BOM and easy eda file
