### ISSUE TITLE
Can I sell this hardware in Taobao?

### ISSUE THREAD

**Issue by wx85105157** [free-pdk/easy-pdk-programmer-hardware#10]
Can I sell this hardware in Taobao?

**Comment by spth** [comment]
https://github.com/free-pdk/easy-pdk-programmer-hardware/blob/master/LICENSE

**Comment by wx85105157** [comment]
thanks very much~

**Comment by cpldcpu** [comment]
Would be great if you could also sell on Aliexpress so people outside China could order it.

**Comment by Dysiexla** [comment]
Yes @wx85105157, there is much demand internationally. Examples:

https://jaycarlson.net/2019/09/06/whats-up-with-these-3-cent-microcontrollers/
https://www.eevblog.com/forum/blog/eevblog-1144-padauk-programmer-reverse-engineering/

**Comment by Kashouryo** [comment]
@wx85105157 Wang, are you selling this device on taobao? If you are, can you please drop a link of the product page?
