### ISSUE TITLE
Documentation: User Manual

### ISSUE THREAD

**Issue by Zitt** [free-pdk/easy-pdk-programmer-hardware#13]
Is there a user manual somewhere? 
Specifically; I'm looking for the definition of the three LEDs tied to PC12-15. 
What purpose does each serve?

**Comment by freepdk** [comment]
Hi,

Right now the 3 LEDs are used for the following purposes:

LED3 : active during probing/reading/writing/running (outer most LED)
LED2: active when UART sends data to IC (when running a program)
LED1 : active when UART receives data from IC (when running a program on IC and IC sends data) 

In firmware source code in file "fpdkusb.c" you can see the definition:

```
static const uint32_t FPDK_LED_UART_RX = 1;                                        
static const uint32_t FPDK_LED_UART_TX = 2;                                        
static const uint32_t FPDK_LED_IC      = 3;
```

This means LED1+2 will only light up when you use the UART (see UART demo programs).

**Comment by Zitt** [comment]
Closing.
