### ISSUE TITLE
How should I program the STM32?

### ISSUE THREAD

**Issue by datedave** [free-pdk/easy-pdk-programmer-hardware#19]
Hi,  I wanna have a go a programming some PMS150C devices, and so need a programmer....

So forgive the dumb question (and not sure the best way to ask..), but how should I programme the STM32 that is on the board? 
Is the on board USB used to program the STM32?
what programming software should I use to program the STM32? 

thanks

**Comment by spth** [comment]
This information can be found in the repository for the software, in particular in thr README for the firmware that goes onto the STM32 (summary: use the on-board USB with dfu-util):
https://github.com/free-pdk/easy-pdk-programmer-software/tree/master/Firmware
