### ISSUE TITLE
SWD pin

### ISSUE THREAD

**Issue by Skywalkerf34** [free-pdk/easy-pdk-programmer-hardware#21]
Hello,

thanks for sharing  this really cool project
I have do assembly for few of those and trying to understand

What is usage of SWD ?

Do you have any schematic/PCB design available for Eagle PCB

Rgds

**Comment by freepdk** [comment]
SWD is a protocol like JTAG. The pins can be used to connect a debug probe like "STLinkV2" during development of the firmware for the programmer.

https://en.wikipedia.org/wiki/JTAG#Similar_interface_standards

Schematics for easyeda ( https://easyeda.com/ ) are in this repository. Eagle is not available

**Comment by benlovage** [comment]
What's the pinout on the SWD header? If everything works, connecting the ground pin and using the guess-and-check method should be a viable way to figure out the pin order, but if something's wrong, not knowing the pins would make debugging the circuit a PITA.

**Comment by freepdk** [comment]
Hmmm... you are right, 2 SWD pins are not labeld in schematics.

But, SWD has only 4 pins (VCC,GND,SWDIO,SWDCLK). 
Pin 1 (square) is shown in schematics as 3.3V and Pin 4 is GND.

So you only would need to try 2 possibilities. Chances that you get it right first time is 50%  :-)

For your reference:

Pin1 (squared): 3.3V
Pin2: SWDIO
Pin3: SWDCLK
Pin4: GND
