### ISSUE TITLE
PCB bill of materials: LCSC part number C177602 no longer exists

### ISSUE THREAD

**Issue by basilhussain** [free-pdk/easy-pdk-programmer-hardware#27]
In the included bill of materials, the listed LCSC part number for the 240k resistors, C177602, no longer exists at LCSC. As in, not "out of stock", but just completely doesn't exist - you will find no results returned when searching for that part number.

This means that when using the 'BOM Tool' at the LCSC website to import the list of parts, the 240k resistors will be missed out.

I suggest a replacement part number: [C144679](https://www.lcsc.com/product-detail/Chip-Resistor-Surface-Mount_YAGEO-AC0603FR-07240KL_C144679.html).

**Comment by cpldcpu** [comment]
Thank you for this input! Can you submit a pull request?
