### ISSUE TITLE
Modify the EASYEDA question

### ISSUE THREAD

**Issue by themindfactory** [free-pdk/easy-pdk-programmer-hardware#3]
I want to modify the SCH and PCB, online I load the SCH and PCB but when you change the SCH it does not change the PCB how do you sync them?? Thanks!

**Comment by freepdk** [comment]
This is an EASYEDA specific question. They have a dedicated user forum for this kinf od questions.

As far as I remember: Inside of EASYEDA there is a "Update PCB" button in PCB view. For this to work both SCH and PCB must be in same project.

**Comment by themindfactory** [comment]
Thanks, never thought of "other" forum... duh.... nice programmer for Padauk! thanks!
