### ISSUE TITLE
Suggestion: Pin 1 indication on silkscreen

### ISSUE THREAD

**Issue by jacobjennings** [free-pdk/easy-pdk-programmer-hardware#4]
For components which might be in the wrong orientation, a dot for pin 1 near the correct corner would be helpful. Same for diode direction

**Comment by freepdk** [comment]
Hi,

In PCB folder is a file "easypdkprog_pcb12_component_placement.pdf" which has the dots like you asking for.

On such small boards it is not feasible to include silk screen, but with the document from above it is relatively easy to assemble.
